/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AddUserToTeamRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AddUserToTeamRequestTests
    {
        // TODO uncomment below to declare an instance variable for AddUserToTeamRequest
        //private AddUserToTeamRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddUserToTeamRequest
            //instance = new AddUserToTeamRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddUserToTeamRequest
        /// </summary>
        [Test]
        public void AddUserToTeamRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AddUserToTeamRequest
            //Assert.IsInstanceOfType<AddUserToTeamRequest> (instance, "variable 'instance' is a AddUserToTeamRequest");
        }


        /// <summary>
        /// Test the property 'TeamId'
        /// </summary>
        [Test]
        public void TeamIdTest()
        {
            // TODO unit test for the property 'TeamId'
        }
        /// <summary>
        /// Test the property 'UserIsTeamManager'
        /// </summary>
        [Test]
        public void UserIsTeamManagerTest()
        {
            // TODO unit test for the property 'UserIsTeamManager'
        }
        /// <summary>
        /// Test the property 'UserRecordId'
        /// </summary>
        [Test]
        public void UserRecordIdTest()
        {
            // TODO unit test for the property 'UserRecordId'
        }

    }

}
