/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BatchSaveRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BatchSaveRequestTests
    {
        // TODO uncomment below to declare an instance variable for BatchSaveRequest
        //private BatchSaveRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BatchSaveRequest
            //instance = new BatchSaveRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BatchSaveRequest
        /// </summary>
        [Test]
        public void BatchSaveRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BatchSaveRequest
            //Assert.IsInstanceOfType<BatchSaveRequest> (instance, "variable 'instance' is a BatchSaveRequest");
        }


        /// <summary>
        /// Test the property 'SaveRequests'
        /// </summary>
        [Test]
        public void SaveRequestsTest()
        {
            // TODO unit test for the property 'SaveRequests'
        }
        /// <summary>
        /// Test the property 'StopOnError'
        /// </summary>
        [Test]
        public void StopOnErrorTest()
        {
            // TODO unit test for the property 'StopOnError'
        }

    }

}
