/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FieldValuesLookupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FieldValuesLookupRequestTests
    {
        // TODO uncomment below to declare an instance variable for FieldValuesLookupRequest
        //private FieldValuesLookupRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FieldValuesLookupRequest
            //instance = new FieldValuesLookupRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FieldValuesLookupRequest
        /// </summary>
        [Test]
        public void FieldValuesLookupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FieldValuesLookupRequest
            //Assert.IsInstanceOfType<FieldValuesLookupRequest> (instance, "variable 'instance' is a FieldValuesLookupRequest");
        }


        /// <summary>
        /// Test the property 'BusbPublicId'
        /// </summary>
        [Test]
        public void BusbPublicIdTest()
        {
            // TODO unit test for the property 'BusbPublicId'
        }
        /// <summary>
        /// Test the property 'BusObId'
        /// </summary>
        [Test]
        public void BusObIdTest()
        {
            // TODO unit test for the property 'BusObId'
        }
        /// <summary>
        /// Test the property 'BusObRecId'
        /// </summary>
        [Test]
        public void BusObRecIdTest()
        {
            // TODO unit test for the property 'BusObRecId'
        }
        /// <summary>
        /// Test the property 'FieldId'
        /// </summary>
        [Test]
        public void FieldIdTest()
        {
            // TODO unit test for the property 'FieldId'
        }
        /// <summary>
        /// Test the property 'FieldName'
        /// </summary>
        [Test]
        public void FieldNameTest()
        {
            // TODO unit test for the property 'FieldName'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Test]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }

    }

}
