/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Prompt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PromptTests
    {
        // TODO uncomment below to declare an instance variable for Prompt
        //private Prompt instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Prompt
            //instance = new Prompt();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Prompt
        /// </summary>
        [Test]
        public void PromptInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Prompt
            //Assert.IsInstanceOfType<Prompt> (instance, "variable 'instance' is a Prompt");
        }


        /// <summary>
        /// Test the property 'AllowValuesOnly'
        /// </summary>
        [Test]
        public void AllowValuesOnlyTest()
        {
            // TODO unit test for the property 'AllowValuesOnly'
        }
        /// <summary>
        /// Test the property 'BusObId'
        /// </summary>
        [Test]
        public void BusObIdTest()
        {
            // TODO unit test for the property 'BusObId'
        }
        /// <summary>
        /// Test the property 'ConstraintXml'
        /// </summary>
        [Test]
        public void ConstraintXmlTest()
        {
            // TODO unit test for the property 'ConstraintXml'
        }
        /// <summary>
        /// Test the property '_Default'
        /// </summary>
        [Test]
        public void _DefaultTest()
        {
            // TODO unit test for the property '_Default'
        }
        /// <summary>
        /// Test the property 'FieldId'
        /// </summary>
        [Test]
        public void FieldIdTest()
        {
            // TODO unit test for the property 'FieldId'
        }
        /// <summary>
        /// Test the property 'IsDateRange'
        /// </summary>
        [Test]
        public void IsDateRangeTest()
        {
            // TODO unit test for the property 'IsDateRange'
        }
        /// <summary>
        /// Test the property 'ListDisplayOption'
        /// </summary>
        [Test]
        public void ListDisplayOptionTest()
        {
            // TODO unit test for the property 'ListDisplayOption'
        }
        /// <summary>
        /// Test the property 'ListReturnFieldId'
        /// </summary>
        [Test]
        public void ListReturnFieldIdTest()
        {
            // TODO unit test for the property 'ListReturnFieldId'
        }
        /// <summary>
        /// Test the property 'MultiLine'
        /// </summary>
        [Test]
        public void MultiLineTest()
        {
            // TODO unit test for the property 'MultiLine'
        }
        /// <summary>
        /// Test the property 'PromptId'
        /// </summary>
        [Test]
        public void PromptIdTest()
        {
            // TODO unit test for the property 'PromptId'
        }
        /// <summary>
        /// Test the property 'PromptType'
        /// </summary>
        [Test]
        public void PromptTypeTest()
        {
            // TODO unit test for the property 'PromptType'
        }
        /// <summary>
        /// Test the property 'PromptTypeName'
        /// </summary>
        [Test]
        public void PromptTypeNameTest()
        {
            // TODO unit test for the property 'PromptTypeName'
        }
        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Test]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Test]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }

    }

}
