/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReadResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReadResponseTests
    {
        // TODO uncomment below to declare an instance variable for ReadResponse
        //private ReadResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReadResponse
            //instance = new ReadResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReadResponse
        /// </summary>
        [Test]
        public void ReadResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReadResponse
            //Assert.IsInstanceOfType<ReadResponse> (instance, "variable 'instance' is a ReadResponse");
        }


        /// <summary>
        /// Test the property 'BusObId'
        /// </summary>
        [Test]
        public void BusObIdTest()
        {
            // TODO unit test for the property 'BusObId'
        }
        /// <summary>
        /// Test the property 'BusObPublicId'
        /// </summary>
        [Test]
        public void BusObPublicIdTest()
        {
            // TODO unit test for the property 'BusObPublicId'
        }
        /// <summary>
        /// Test the property 'BusObRecId'
        /// </summary>
        [Test]
        public void BusObRecIdTest()
        {
            // TODO unit test for the property 'BusObRecId'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Test]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Test]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'HasError'
        /// </summary>
        [Test]
        public void HasErrorTest()
        {
            // TODO unit test for the property 'HasError'
        }

    }

}
