/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RelatedSaveRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RelatedSaveRequestTests
    {
        // TODO uncomment below to declare an instance variable for RelatedSaveRequest
        //private RelatedSaveRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RelatedSaveRequest
            //instance = new RelatedSaveRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RelatedSaveRequest
        /// </summary>
        [Test]
        public void RelatedSaveRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RelatedSaveRequest
            //Assert.IsInstanceOfType<RelatedSaveRequest> (instance, "variable 'instance' is a RelatedSaveRequest");
        }


        /// <summary>
        /// Test the property 'ParentBusObId'
        /// </summary>
        [Test]
        public void ParentBusObIdTest()
        {
            // TODO unit test for the property 'ParentBusObId'
        }
        /// <summary>
        /// Test the property 'ParentBusObPublicId'
        /// </summary>
        [Test]
        public void ParentBusObPublicIdTest()
        {
            // TODO unit test for the property 'ParentBusObPublicId'
        }
        /// <summary>
        /// Test the property 'ParentBusObRecId'
        /// </summary>
        [Test]
        public void ParentBusObRecIdTest()
        {
            // TODO unit test for the property 'ParentBusObRecId'
        }
        /// <summary>
        /// Test the property 'RelationshipId'
        /// </summary>
        [Test]
        public void RelationshipIdTest()
        {
            // TODO unit test for the property 'RelationshipId'
        }
        /// <summary>
        /// Test the property 'BusObId'
        /// </summary>
        [Test]
        public void BusObIdTest()
        {
            // TODO unit test for the property 'BusObId'
        }
        /// <summary>
        /// Test the property 'BusObPublicId'
        /// </summary>
        [Test]
        public void BusObPublicIdTest()
        {
            // TODO unit test for the property 'BusObPublicId'
        }
        /// <summary>
        /// Test the property 'BusObRecId'
        /// </summary>
        [Test]
        public void BusObRecIdTest()
        {
            // TODO unit test for the property 'BusObRecId'
        }
        /// <summary>
        /// Test the property 'Fields'
        /// </summary>
        [Test]
        public void FieldsTest()
        {
            // TODO unit test for the property 'Fields'
        }

    }

}
