/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RelatedBusinessObjectResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RelatedBusinessObjectResponseTests
    {
        // TODO uncomment below to declare an instance variable for RelatedBusinessObjectResponse
        //private RelatedBusinessObjectResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RelatedBusinessObjectResponse
            //instance = new RelatedBusinessObjectResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RelatedBusinessObjectResponse
        /// </summary>
        [Test]
        public void RelatedBusinessObjectResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RelatedBusinessObjectResponse
            //Assert.IsInstanceOfType<RelatedBusinessObjectResponse> (instance, "variable 'instance' is a RelatedBusinessObjectResponse");
        }


        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Test]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'HasError'
        /// </summary>
        [Test]
        public void HasErrorTest()
        {
            // TODO unit test for the property 'HasError'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Test]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Test]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'ParentBusObId'
        /// </summary>
        [Test]
        public void ParentBusObIdTest()
        {
            // TODO unit test for the property 'ParentBusObId'
        }
        /// <summary>
        /// Test the property 'ParentBusObPublicId'
        /// </summary>
        [Test]
        public void ParentBusObPublicIdTest()
        {
            // TODO unit test for the property 'ParentBusObPublicId'
        }
        /// <summary>
        /// Test the property 'ParentBusObRecId'
        /// </summary>
        [Test]
        public void ParentBusObRecIdTest()
        {
            // TODO unit test for the property 'ParentBusObRecId'
        }
        /// <summary>
        /// Test the property 'RelatedBusinessObjects'
        /// </summary>
        [Test]
        public void RelatedBusinessObjectsTest()
        {
            // TODO unit test for the property 'RelatedBusinessObjects'
        }
        /// <summary>
        /// Test the property 'RelationshipId'
        /// </summary>
        [Test]
        public void RelationshipIdTest()
        {
            // TODO unit test for the property 'RelationshipId'
        }
        /// <summary>
        /// Test the property 'TotalRecords'
        /// </summary>
        [Test]
        public void TotalRecordsTest()
        {
            // TODO unit test for the property 'TotalRecords'
        }

    }

}
