/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RelatedSaveResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RelatedSaveResponseTests
    {
        // TODO uncomment below to declare an instance variable for RelatedSaveResponse
        //private RelatedSaveResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RelatedSaveResponse
            //instance = new RelatedSaveResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RelatedSaveResponse
        /// </summary>
        [Test]
        public void RelatedSaveResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RelatedSaveResponse
            //Assert.IsInstanceOfType<RelatedSaveResponse> (instance, "variable 'instance' is a RelatedSaveResponse");
        }


        /// <summary>
        /// Test the property 'ParentBusObId'
        /// </summary>
        [Test]
        public void ParentBusObIdTest()
        {
            // TODO unit test for the property 'ParentBusObId'
        }
        /// <summary>
        /// Test the property 'ParentBusObPublicId'
        /// </summary>
        [Test]
        public void ParentBusObPublicIdTest()
        {
            // TODO unit test for the property 'ParentBusObPublicId'
        }
        /// <summary>
        /// Test the property 'ParentBusObRecId'
        /// </summary>
        [Test]
        public void ParentBusObRecIdTest()
        {
            // TODO unit test for the property 'ParentBusObRecId'
        }
        /// <summary>
        /// Test the property 'RelationshipId'
        /// </summary>
        [Test]
        public void RelationshipIdTest()
        {
            // TODO unit test for the property 'RelationshipId'
        }
        /// <summary>
        /// Test the property 'BusObPublicId'
        /// </summary>
        [Test]
        public void BusObPublicIdTest()
        {
            // TODO unit test for the property 'BusObPublicId'
        }
        /// <summary>
        /// Test the property 'BusObRecId'
        /// </summary>
        [Test]
        public void BusObRecIdTest()
        {
            // TODO unit test for the property 'BusObRecId'
        }
        /// <summary>
        /// Test the property 'FieldValidationErrors'
        /// </summary>
        [Test]
        public void FieldValidationErrorsTest()
        {
            // TODO unit test for the property 'FieldValidationErrors'
        }
        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Test]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'HasError'
        /// </summary>
        [Test]
        public void HasErrorTest()
        {
            // TODO unit test for the property 'HasError'
        }

    }

}
