/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Role
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RoleTests
    {
        // TODO uncomment below to declare an instance variable for Role
        //private Role instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Role
            //instance = new Role();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Role
        /// </summary>
        [Test]
        public void RoleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Role
            //Assert.IsInstanceOfType<Role> (instance, "variable 'instance' is a Role");
        }


        /// <summary>
        /// Test the property 'BrowserClientCustomViewId'
        /// </summary>
        [Test]
        public void BrowserClientCustomViewIdTest()
        {
            // TODO unit test for the property 'BrowserClientCustomViewId'
        }
        /// <summary>
        /// Test the property 'BusinessObjectExcludeList'
        /// </summary>
        [Test]
        public void BusinessObjectExcludeListTest()
        {
            // TODO unit test for the property 'BusinessObjectExcludeList'
        }
        /// <summary>
        /// Test the property 'Culture'
        /// </summary>
        [Test]
        public void CultureTest()
        {
            // TODO unit test for the property 'Culture'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'MobileClientCustomViewId'
        /// </summary>
        [Test]
        public void MobileClientCustomViewIdTest()
        {
            // TODO unit test for the property 'MobileClientCustomViewId'
        }
        /// <summary>
        /// Test the property 'PrimaryBusObId'
        /// </summary>
        [Test]
        public void PrimaryBusObIdTest()
        {
            // TODO unit test for the property 'PrimaryBusObId'
        }
        /// <summary>
        /// Test the property 'RoleId'
        /// </summary>
        [Test]
        public void RoleIdTest()
        {
            // TODO unit test for the property 'RoleId'
        }
        /// <summary>
        /// Test the property 'RoleName'
        /// </summary>
        [Test]
        public void RoleNameTest()
        {
            // TODO unit test for the property 'RoleName'
        }
        /// <summary>
        /// Test the property 'SmartClientCustomViewId'
        /// </summary>
        [Test]
        public void SmartClientCustomViewIdTest()
        {
            // TODO unit test for the property 'SmartClientCustomViewId'
        }

    }

}
