/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SaveUrlAttachmentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SaveUrlAttachmentRequestTests
    {
        // TODO uncomment below to declare an instance variable for SaveUrlAttachmentRequest
        //private SaveUrlAttachmentRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SaveUrlAttachmentRequest
            //instance = new SaveUrlAttachmentRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SaveUrlAttachmentRequest
        /// </summary>
        [Test]
        public void SaveUrlAttachmentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SaveUrlAttachmentRequest
            //Assert.IsInstanceOfType<SaveUrlAttachmentRequest> (instance, "variable 'instance' is a SaveUrlAttachmentRequest");
        }


        /// <summary>
        /// Test the property 'BusObId'
        /// </summary>
        [Test]
        public void BusObIdTest()
        {
            // TODO unit test for the property 'BusObId'
        }
        /// <summary>
        /// Test the property 'BusObName'
        /// </summary>
        [Test]
        public void BusObNameTest()
        {
            // TODO unit test for the property 'BusObName'
        }
        /// <summary>
        /// Test the property 'BusObPublicId'
        /// </summary>
        [Test]
        public void BusObPublicIdTest()
        {
            // TODO unit test for the property 'BusObPublicId'
        }
        /// <summary>
        /// Test the property 'BusObRecId'
        /// </summary>
        [Test]
        public void BusObRecIdTest()
        {
            // TODO unit test for the property 'BusObRecId'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Test]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'DisplayText'
        /// </summary>
        [Test]
        public void DisplayTextTest()
        {
            // TODO unit test for the property 'DisplayText'
        }
        /// <summary>
        /// Test the property 'IncludeLinks'
        /// </summary>
        [Test]
        public void IncludeLinksTest()
        {
            // TODO unit test for the property 'IncludeLinks'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
