/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SaveBusObAttachmentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SaveBusObAttachmentRequestTests
    {
        // TODO uncomment below to declare an instance variable for SaveBusObAttachmentRequest
        //private SaveBusObAttachmentRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SaveBusObAttachmentRequest
            //instance = new SaveBusObAttachmentRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SaveBusObAttachmentRequest
        /// </summary>
        [Test]
        public void SaveBusObAttachmentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SaveBusObAttachmentRequest
            //Assert.IsInstanceOfType<SaveBusObAttachmentRequest> (instance, "variable 'instance' is a SaveBusObAttachmentRequest");
        }


        /// <summary>
        /// Test the property 'AttachBusObId'
        /// </summary>
        [Test]
        public void AttachBusObIdTest()
        {
            // TODO unit test for the property 'AttachBusObId'
        }
        /// <summary>
        /// Test the property 'AttachBusObName'
        /// </summary>
        [Test]
        public void AttachBusObNameTest()
        {
            // TODO unit test for the property 'AttachBusObName'
        }
        /// <summary>
        /// Test the property 'AttachBusObPublicId'
        /// </summary>
        [Test]
        public void AttachBusObPublicIdTest()
        {
            // TODO unit test for the property 'AttachBusObPublicId'
        }
        /// <summary>
        /// Test the property 'AttachBusObRecId'
        /// </summary>
        [Test]
        public void AttachBusObRecIdTest()
        {
            // TODO unit test for the property 'AttachBusObRecId'
        }
        /// <summary>
        /// Test the property 'BusObId'
        /// </summary>
        [Test]
        public void BusObIdTest()
        {
            // TODO unit test for the property 'BusObId'
        }
        /// <summary>
        /// Test the property 'BusObName'
        /// </summary>
        [Test]
        public void BusObNameTest()
        {
            // TODO unit test for the property 'BusObName'
        }
        /// <summary>
        /// Test the property 'BusObPublicId'
        /// </summary>
        [Test]
        public void BusObPublicIdTest()
        {
            // TODO unit test for the property 'BusObPublicId'
        }
        /// <summary>
        /// Test the property 'BusObRecId'
        /// </summary>
        [Test]
        public void BusObRecIdTest()
        {
            // TODO unit test for the property 'BusObRecId'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Test]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'IncludeLinks'
        /// </summary>
        [Test]
        public void IncludeLinksTest()
        {
            // TODO unit test for the property 'IncludeLinks'
        }

    }

}
