/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SchemaResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SchemaResponseTests
    {
        // TODO uncomment below to declare an instance variable for SchemaResponse
        //private SchemaResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SchemaResponse
            //instance = new SchemaResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchemaResponse
        /// </summary>
        [Test]
        public void SchemaResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SchemaResponse
            //Assert.IsInstanceOfType<SchemaResponse> (instance, "variable 'instance' is a SchemaResponse");
        }


        /// <summary>
        /// Test the property 'BusObId'
        /// </summary>
        [Test]
        public void BusObIdTest()
        {
            // TODO unit test for the property 'BusObId'
        }
        /// <summary>
        /// Test the property 'FieldDefinitions'
        /// </summary>
        [Test]
        public void FieldDefinitionsTest()
        {
            // TODO unit test for the property 'FieldDefinitions'
        }
        /// <summary>
        /// Test the property 'FirstRecIdField'
        /// </summary>
        [Test]
        public void FirstRecIdFieldTest()
        {
            // TODO unit test for the property 'FirstRecIdField'
        }
        /// <summary>
        /// Test the property 'GridDefinitions'
        /// </summary>
        [Test]
        public void GridDefinitionsTest()
        {
            // TODO unit test for the property 'GridDefinitions'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RecIdFields'
        /// </summary>
        [Test]
        public void RecIdFieldsTest()
        {
            // TODO unit test for the property 'RecIdFields'
        }
        /// <summary>
        /// Test the property 'Relationships'
        /// </summary>
        [Test]
        public void RelationshipsTest()
        {
            // TODO unit test for the property 'Relationships'
        }
        /// <summary>
        /// Test the property 'StateFieldId'
        /// </summary>
        [Test]
        public void StateFieldIdTest()
        {
            // TODO unit test for the property 'StateFieldId'
        }
        /// <summary>
        /// Test the property 'States'
        /// </summary>
        [Test]
        public void StatesTest()
        {
            // TODO unit test for the property 'States'
        }
        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Test]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'HasError'
        /// </summary>
        [Test]
        public void HasErrorTest()
        {
            // TODO unit test for the property 'HasError'
        }

    }

}
