/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SimpleResultsListItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SimpleResultsListItemTests
    {
        // TODO uncomment below to declare an instance variable for SimpleResultsListItem
        //private SimpleResultsListItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SimpleResultsListItem
            //instance = new SimpleResultsListItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SimpleResultsListItem
        /// </summary>
        [Test]
        public void SimpleResultsListItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SimpleResultsListItem
            //Assert.IsInstanceOfType<SimpleResultsListItem> (instance, "variable 'instance' is a SimpleResultsListItem");
        }


        /// <summary>
        /// Test the property 'BusObId'
        /// </summary>
        [Test]
        public void BusObIdTest()
        {
            // TODO unit test for the property 'BusObId'
        }
        /// <summary>
        /// Test the property 'BusObRecId'
        /// </summary>
        [Test]
        public void BusObRecIdTest()
        {
            // TODO unit test for the property 'BusObRecId'
        }
        /// <summary>
        /// Test the property 'DocRepositoryItemId'
        /// </summary>
        [Test]
        public void DocRepositoryItemIdTest()
        {
            // TODO unit test for the property 'DocRepositoryItemId'
        }
        /// <summary>
        /// Test the property 'GalleryImage'
        /// </summary>
        [Test]
        public void GalleryImageTest()
        {
            // TODO unit test for the property 'GalleryImage'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'PublicId'
        /// </summary>
        [Test]
        public void PublicIdTest()
        {
            // TODO unit test for the property 'PublicId'
        }
        /// <summary>
        /// Test the property 'Scope'
        /// </summary>
        [Test]
        public void ScopeTest()
        {
            // TODO unit test for the property 'Scope'
        }
        /// <summary>
        /// Test the property 'ScopeOwner'
        /// </summary>
        [Test]
        public void ScopeOwnerTest()
        {
            // TODO unit test for the property 'ScopeOwner'
        }
        /// <summary>
        /// Test the property 'SubTitle'
        /// </summary>
        [Test]
        public void SubTitleTest()
        {
            // TODO unit test for the property 'SubTitle'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
