/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TeamSaveRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TeamSaveRequestTests
    {
        // TODO uncomment below to declare an instance variable for TeamSaveRequest
        //private TeamSaveRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TeamSaveRequest
            //instance = new TeamSaveRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TeamSaveRequest
        /// </summary>
        [Test]
        public void TeamSaveRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamSaveRequest
            //Assert.IsInstanceOfType<TeamSaveRequest> (instance, "variable 'instance' is a TeamSaveRequest");
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'EmailAlias'
        /// </summary>
        [Test]
        public void EmailAliasTest()
        {
            // TODO unit test for the property 'EmailAlias'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'TeamId'
        /// </summary>
        [Test]
        public void TeamIdTest()
        {
            // TODO unit test for the property 'TeamId'
        }
        /// <summary>
        /// Test the property 'TeamName'
        /// </summary>
        [Test]
        public void TeamNameTest()
        {
            // TODO unit test for the property 'TeamName'
        }
        /// <summary>
        /// Test the property 'TeamType'
        /// </summary>
        [Test]
        public void TeamTypeTest()
        {
            // TODO unit test for the property 'TeamType'
        }

    }

}
