/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserBatchSaveV2Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserBatchSaveV2ResponseTests
    {
        // TODO uncomment below to declare an instance variable for UserBatchSaveV2Response
        //private UserBatchSaveV2Response instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserBatchSaveV2Response
            //instance = new UserBatchSaveV2Response();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserBatchSaveV2Response
        /// </summary>
        [Test]
        public void UserBatchSaveV2ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserBatchSaveV2Response
            //Assert.IsInstanceOfType<UserBatchSaveV2Response> (instance, "variable 'instance' is a UserBatchSaveV2Response");
        }


        /// <summary>
        /// Test the property 'Responses'
        /// </summary>
        [Test]
        public void ResponsesTest()
        {
            // TODO unit test for the property 'Responses'
        }
        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Test]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'HasError'
        /// </summary>
        [Test]
        public void HasErrorTest()
        {
            // TODO unit test for the property 'HasError'
        }

    }

}
