/* 
 * Cherwell Rest API
 *
 * <a href=\"../../index.html\">Cherwell Rest API Documentation</a><br>Select version options from the header drop-down list (to the left of the Client Key box). Then, click Explore to view different versions of operations.
 *
 * OpenAPI spec version: 9.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TemplateRequest
    /// </summary>
    [DataContract]
    public partial class TemplateRequest :  IEquatable<TemplateRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateRequest" /> class.
        /// </summary>
        /// <param name="BusObId">BusObId.</param>
        /// <param name="FieldNames">FieldNames.</param>
        /// <param name="FieldIds">FieldIds.</param>
        /// <param name="IncludeAll">IncludeAll.</param>
        /// <param name="IncludeRequired">IncludeRequired.</param>
        public TemplateRequest(string BusObId = default(string), List<string> FieldNames = default(List<string>), List<string> FieldIds = default(List<string>), bool? IncludeAll = default(bool?), bool? IncludeRequired = default(bool?))
        {
            this.BusObId = BusObId;
            this.FieldNames = FieldNames;
            this.FieldIds = FieldIds;
            this.IncludeAll = IncludeAll;
            this.IncludeRequired = IncludeRequired;
        }
        
        /// <summary>
        /// Gets or Sets BusObId
        /// </summary>
        [DataMember(Name="busObId", EmitDefaultValue=false)]
        public string BusObId { get; set; }

        /// <summary>
        /// Gets or Sets FieldNames
        /// </summary>
        [DataMember(Name="fieldNames", EmitDefaultValue=false)]
        public List<string> FieldNames { get; set; }

        /// <summary>
        /// Gets or Sets FieldIds
        /// </summary>
        [DataMember(Name="fieldIds", EmitDefaultValue=false)]
        public List<string> FieldIds { get; set; }

        /// <summary>
        /// Gets or Sets IncludeAll
        /// </summary>
        [DataMember(Name="includeAll", EmitDefaultValue=false)]
        public bool? IncludeAll { get; set; }

        /// <summary>
        /// Gets or Sets IncludeRequired
        /// </summary>
        [DataMember(Name="includeRequired", EmitDefaultValue=false)]
        public bool? IncludeRequired { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TemplateRequest {\n");
            sb.Append("  BusObId: ").Append(BusObId).Append("\n");
            sb.Append("  FieldNames: ").Append(FieldNames).Append("\n");
            sb.Append("  FieldIds: ").Append(FieldIds).Append("\n");
            sb.Append("  IncludeAll: ").Append(IncludeAll).Append("\n");
            sb.Append("  IncludeRequired: ").Append(IncludeRequired).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TemplateRequest);
        }

        /// <summary>
        /// Returns true if TemplateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TemplateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TemplateRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BusObId == input.BusObId ||
                    (this.BusObId != null &&
                    this.BusObId.Equals(input.BusObId))
                ) && 
                (
                    this.FieldNames == input.FieldNames ||
                    this.FieldNames != null &&
                    this.FieldNames.SequenceEqual(input.FieldNames)
                ) && 
                (
                    this.FieldIds == input.FieldIds ||
                    this.FieldIds != null &&
                    this.FieldIds.SequenceEqual(input.FieldIds)
                ) && 
                (
                    this.IncludeAll == input.IncludeAll ||
                    (this.IncludeAll != null &&
                    this.IncludeAll.Equals(input.IncludeAll))
                ) && 
                (
                    this.IncludeRequired == input.IncludeRequired ||
                    (this.IncludeRequired != null &&
                    this.IncludeRequired.Equals(input.IncludeRequired))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BusObId != null)
                    hashCode = hashCode * 59 + this.BusObId.GetHashCode();
                if (this.FieldNames != null)
                    hashCode = hashCode * 59 + this.FieldNames.GetHashCode();
                if (this.FieldIds != null)
                    hashCode = hashCode * 59 + this.FieldIds.GetHashCode();
                if (this.IncludeAll != null)
                    hashCode = hashCode * 59 + this.IncludeAll.GetHashCode();
                if (this.IncludeRequired != null)
                    hashCode = hashCode * 59 + this.IncludeRequired.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
